#!/usr/bin/python

# +----------------------------------------------------------------------+
# |                                                                      |
# |       _                      _   __  __                              |
# |      | |                    | | |  \/  |                             |
# |      | |_   _ _ __   ___  __| | | \  / | ___ _ __ ___   ___  _ __    |
# |  _   | | | | | '_ \ / _ \/ _` | | |\/| |/ _ \ '_ ` _ \ / _ \| '_ \   |
# | | |__| | |_| | | | |  __/ (_| | | |  | |  __/ | | | | | (_) | | | |  |
# |  \____/ \__,_|_| |_|\___|\__,_| |_|  |_|\___|_| |_| |_|\___/|_| |_|  |
# |                                                                      |
# | Author : Juned Memon            Email : junedm@tipsntraps.com        |
# +----------------------------------------------------------------------+

# +----------------------------------------------------------------------+
# | Version : 1.0                                                        
# | Script  : myrole                                                     
# | Notes   : myrole, will be part of `james` to take the auto-inventory
# |           of plugin check_myrole.Which will have all the role and build information.
# | 
# | Sample output of check_myrole is as below
# |<<<myrole>>>
# |Myrole Environment:Production,Project:DevOPS,Role:ShellServer,Build:DEP-786,Site:Colo                                                                     
# +----------------------------------------------------------------------+


def inventory_myrole(info):
   inventory = []

   for line in info:
      key = line[0]   
      value = line[1]  

      if key in ("Myrole") :
          inventory.append( (key, None) )

   return inventory

def check_myrole(item, params, info):
    for line in info:
      if line[0] == item :
         build = line[1]
         return (0, "%s" % build)


# declare the check to Check_MK
#check_info["myrole"] = {
#    'check_function':            check_myrole,
#    'inventory_function':        inventory_myrole,
#    'service_description':       '%s',
#}
check_info["myrole"] = (check_myrole, "%s", 1, inventory_myrole)

